[workspace]
members = [
    "stitchkit",
    "stitchkit-archive",
    "stitchkit-core",
    "stitchkit-reflection-types",
]

[workspace.dependencies]
anyhow = "1.0.69"
bitflags = "2.0.0-rc.2"
uuid = "1.3.0"
tracing = "0.1.37"

stitchkit-archive = { path = "stitchkit-archive" }
stitchkit-core = { path = "stitchkit-core" }
stitchkit-reflection-types = { path = "stitchkit-reflection-types" }
