[workspace]
members = [
    "stitchkit",
    "stitchkit-archive",
    "stitchkit-core",
]

[workspace.dependencies]
anyhow = "1.0.69"
uuid = "1.3.0"
tracing = "0.1.37"

stitchkit-archive = { path = "stitchkit-archive" }
stitchkit-core = { path = "stitchkit-core" }
