[package]
name = "stitchkit-core-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "1.0.107"
