[package]
name = "muscript-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
heck = "0.4.1"
indexmap = "1.9.2"
indoc = { workspace = true }
tracing = { workspace = true }

muscript-foundation = { workspace = true }
muscript-syntax = { workspace = true }
