[package]
name = "muscript-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
indexmap = "1.9.2"

muscript-foundation = { workspace = true }
muscript-syntax = { workspace = true }
