[package]
name = "muscript-foundation"
version = "0.1.0"
edition = "2021"

[dependencies]
ref-cast = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

codespan-reporting = "0.11.1"
